#ifndef GABRIEL__BASE__DEFINE
#define GABRIEL__BASE__DEFINE

#include "ace/Basic_Types.h"

typedef ACE_INT8 int8;
typedef ACE_UINT8 uint8;
typedef ACE_INT16 int16;
typedef ACE_UINT16 uint16;
typedef ACE_INT32 int32;
typedef ACE_UINT32 uint32;
typedef ACE_INT64 int64;
typedef ACE_UINT64 uint64;

#define MIN_INT8 ACE_CHAR_MIN
#define MAX_INT8 ACE_CHAR_MAX
#define MAX_UINT8 ACE_OCTET_MAX

#define MIN_INT16 ACE_INT16_MIN
#define MAX_INT16 ACE_INT16_MAX
#define MAX_UINT16 ACE_UINT16_MAX

#define MIN_INT32 ACE_INT32_MIN
#define MAX_INT32 ACE_INT32_MAX
#define MAX_UINT32 ACE_UINT32_MAX

#define MIN_INT64 ACE_INT64_MIN
#define MAX_INT64 ACE_INT64_MAX
#define MAX_UINT64 ACE_UINT64_MAX

#define MIN_FLOAT ACE_FLT_MIN
#define MAX_FLOAT ACE_FLT_MAX

#define MIN_DOUBLE ACE_DBL_MIN
#define MAX_DOUBLE ACE_DBL_MAX

#endif
